name: Python Lint and Format
on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pipenv
          pipenv --python $(which python)
          PIPENV_SHELL_FANCY=1
          pipenv shell
      - name: Lint check
        run: |
          pylint **/*.py
      - name: Format check
        run: |
          black --diff --check **/*.py
